#!/usr/bin/env python

import qckt
import qckt.backend as bknd
import qckt.noisemodel as ns

def ghz_ck(n_qubits: int):
    ck = qckt.QCkt(n_qubits)
    ck.H(0)
    for ii in range(0, n_qubits-1):
        ck.CX(ii,ii+1)
    return ck

print('bit_flip')
ck = ghz_ck(3)
noiseop = ns.bit_flip(0.1)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('depolarizing')
ck = ghz_ck(3)
noiseop = ns.depolarizing(0.1)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('phase_flip')
ck = ghz_ck(3)
noiseop = ns.phase_flip(0.1)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('amplitude_damping')
ck = ghz_ck(3)
noiseop = ns.amplitude_damping(0.1)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('generalized amplitude_damping')
ck = ghz_ck(3)
noiseop = ns.generalized_amplitude_damping(gamma=0.1, probability=0.1)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('phase_damping')
ck = ghz_ck(3)
noiseop = ns.phase_damping(gamma=0.1)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('pauli_channel')
ck = ghz_ck(3)
noiseop = ns.pauli_channel(probx=0.1, proby=0.2, probz=0.3)
noise_profile = ns.NoiseProfile(noise_chan_allgates=ns.NoiseChannelSequence(noiseop))
ck.set_noise_profile(noise_profile=noise_profile)
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('two_qubit_dephasing')
ck = qckt.QCkt(2,2)
ck.H([0,1])
ck.NOISE(ns.two_qubit_dephasing(probability=0.1),[0,1])
ck.H([0,1])
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)

print('two_qubit_depolarizing')
ck = qckt.QCkt(2,2)
ck.H(0)
ck.CX(0,1)
ck.CX.set_noise_on_all(ns.two_qubit_depolarizing(probability=0.1))
ck.draw()
job = qckt.Job(ck)
bk = bknd.DMQdeb()
bk.runjob(job=job)
svec = job.get_svec()
print(svec)
