import qckt
import numpy as np
from QSystems import *
from Job import Job

# Test 01
ck = qckt.QCkt(4)
ck.X(0)
ck.H(1)
ck.CX(1,2)
ck.draw()
job = Job(ck)
NISQdeb().runjob(job)
print("STATE VECTOR READ OUT")
print(job.get_svec())
print("CREGISTER READ OUT: ",end="")
print()
print(job.get_creg()[0])

# Test 02
ck = qckt.QCkt(4)
ck.X(0)
ck.H(1)
ck.H(2)
ck.CCX(1,2,3)
ck.draw()
job = Job(ck)
NISQdeb().runjob(job)
print("STATE VECTOR READ OUT")
print(job.get_svec())
print("CREGISTER READ OUT: ",end="")
print()
print(job.get_creg()[0])

# Test 03
ck = qckt.QCkt(4,4)
ck.X(0)
ck.X(1)
ck.X(2)
ck.X(0)
ck.Y(1)
ck.Z(2)
ck.M([2,1,0])
ck.draw()
job = Job(ck)
NISQdeb().runjob(job)
print("STATE VECTOR READ OUT")
print(job.get_svec())
print("CREGISTER READ OUT: ",end="")
print()
print(job.get_creg()[0])

# Test 04
ck = qckt.QCkt(6)
ck.X(0)
ck.X(1)
ck.X(4)
ck.P(np.pi/4.0,0)
ck.CP(np.pi/4.0,1,4)
ck.CP(np.pi/4.0,2,5)
ck.draw()
job = Job(ck)
NISQdeb().runjob(job)
print("STATE VECTOR READ OUT")
print(job.get_svec())
print("CREGISTER READ OUT: ",end="")
print()
print(job.get_creg()[0])

# Test 05
ck = qckt.QCkt(6)
ck.X(0)
ck.UROTk(3,0)
ck.SWAP(0,4)
ck.draw()
job = Job(ck)
NISQdeb().runjob(job)
print("STATE VECTOR READ OUT")
print(job.get_svec())
print("CREGISTER READ OUT: ",end="")
print()
print(job.get_creg()[0])

# Test 06
ck = qckt.QCkt(6)
ck.X(0)
ck.X(2)
ck.X(4)
ck.Border()
ck.QFT(4,3,2,1,0)
ck.Border()
ck.draw()
job = Job(ck)
NISQdeb().runjob(job)
print("STATE VECTOR READ OUT")
print(job.get_svec())
print("CREGISTER READ OUT: ",end="")
print()
print(job.get_creg()[0])
